# Generated by Django 6.0.2 on 2026-03-04 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sala', '0002_sala_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('horario', models.CharField(choices=[('mañana', 'Manana'), ('mediodia', 'Mediodia'), ('noche', 'Noche')], max_length=8)),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10)),
                ('id_sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sala.sala')),
            ],
        ),
    ]
