# Generated by Django 6.0.2 on 2026-03-04 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasala',
            old_name='id_sala',
            new_name='sala',
        ),
    ]
