# Generated by Django 6.0.2 on 2026-03-04 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_rename_id_sala_reservasala_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservasala',
            old_name='sala',
            new_name='id_sala',
        ),
    ]
