# Generated by Django 6.0.2 on 2026-03-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_habitacion', models.IntegerField(unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_personas', models.IntegerField()),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
