# Generated by Django 6.0.2 on 2026-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('habitacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='extras',
            field=models.ManyToManyField(blank=True, to='extras.extras'),
        ),
    ]
