# Generated by Django 6.0.2 on 2026-03-02 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habitacion', '0002_habitacion_extras'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habitacion',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
    ]
