# Generated by Django 6.0.2 on 2026-03-02 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extras', '0001_initial'),
        ('sala', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='extras',
            field=models.ManyToManyField(blank=True, to='extras.extras'),
        ),
    ]
